/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pao;

/**
 *
 * @author Jitca David
 */
import javax.swing.JFrame;
import javax.swing.JOptionPane;
public class loginform extends javax.swing.JFrame {

    /**
     * Creates new form loginform
     */
    public loginform() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanelaLogo = new javax.swing.JPanel();
        jLabelImage = new javax.swing.JLabel();
        jLabelName = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabelMail = new javax.swing.JLabel();
        UserNameField = new javax.swing.JTextField();
        PassWordField = new javax.swing.JPasswordField();
        jLabelPASS = new javax.swing.JLabel();
        CancelButton = new javax.swing.JButton();
        ForgotClick = new javax.swing.JLabel();
        jLabelMinimize = new javax.swing.JLabel();
        jLabelClose = new javax.swing.JLabel();
        LoginButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                formMouseDragged(evt);
            }
        });
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                formMousePressed(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(208, 225, 249));
        jPanel1.setForeground(new java.awt.Color(77, 100, 141));
        jPanel1.setLayout(null);

        jPanelaLogo.setBackground(new java.awt.Color(40, 54, 85));

        jLabelImage.setIcon(new javax.swing.ImageIcon("E:\\Facultate\\SEM II\\ChessGame\\Image\\network.png")); // NOI18N

        jLabelName.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        jLabelName.setForeground(new java.awt.Color(255, 255, 255));
        jLabelName.setText("ChessGame by MasterMinds");

        javax.swing.GroupLayout jPanelaLogoLayout = new javax.swing.GroupLayout(jPanelaLogo);
        jPanelaLogo.setLayout(jPanelaLogoLayout);
        jPanelaLogoLayout.setHorizontalGroup(
            jPanelaLogoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelaLogoLayout.createSequentialGroup()
                .addContainerGap(50, Short.MAX_VALUE)
                .addGroup(jPanelaLogoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabelImage, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabelName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(50, 50, 50))
        );
        jPanelaLogoLayout.setVerticalGroup(
            jPanelaLogoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelaLogoLayout.createSequentialGroup()
                .addGap(151, 151, 151)
                .addComponent(jLabelImage)
                .addGap(18, 18, 18)
                .addComponent(jLabelName)
                .addContainerGap(125, Short.MAX_VALUE))
        );

        jPanel1.add(jPanelaLogo);
        jPanelaLogo.setBounds(0, 0, 0, 460);

        jLabel3.setFont(new java.awt.Font("Calibri", 0, 36)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Login");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(320, 50, 120, 60);

        jLabelMail.setBackground(new java.awt.Color(77, 100, 141));
        jLabelMail.setFont(new java.awt.Font("Calibri", 1, 12)); // NOI18N
        jLabelMail.setForeground(new java.awt.Color(40, 54, 85));
        jLabelMail.setText("User Name");
        jPanel1.add(jLabelMail);
        jLabelMail.setBounds(290, 130, 80, 16);

        UserNameField.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        UserNameField.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        UserNameField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UserNameFieldActionPerformed(evt);
            }
        });
        jPanel1.add(UserNameField);
        UserNameField.setBounds(290, 150, 190, 40);

        PassWordField.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        PassWordField.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        PassWordField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PassWordFieldActionPerformed(evt);
            }
        });
        jPanel1.add(PassWordField);
        PassWordField.setBounds(290, 220, 190, 40);

        jLabelPASS.setFont(new java.awt.Font("Calibri", 1, 12)); // NOI18N
        jLabelPASS.setForeground(new java.awt.Color(40, 54, 85));
        jLabelPASS.setText("Login Password");
        jPanel1.add(jLabelPASS);
        jLabelPASS.setBounds(290, 200, 100, 16);

        CancelButton.setBackground(new java.awt.Color(77, 100, 141));
        CancelButton.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        CancelButton.setForeground(new java.awt.Color(40, 54, 85));
        CancelButton.setText("Cancel");
        CancelButton.setBorder(null);
        CancelButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        CancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CancelButtonActionPerformed(evt);
            }
        });
        jPanel1.add(CancelButton);
        CancelButton.setBounds(290, 300, 70, 30);

        ForgotClick.setFont(new java.awt.Font("Calibri", 1, 12)); // NOI18N
        ForgotClick.setForeground(new java.awt.Color(40, 54, 85));
        ForgotClick.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ForgotClick.setText("Forgot Pasword");
        ForgotClick.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        ForgotClick.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ForgotClickMouseClicked(evt);
            }
        });
        jPanel1.add(ForgotClick);
        ForgotClick.setBounds(290, 360, 200, 16);

        jLabelMinimize.setFont(new java.awt.Font("Calibri", 1, 36)); // NOI18N
        jLabelMinimize.setForeground(new java.awt.Color(40, 54, 85));
        jLabelMinimize.setText("-");
        jLabelMinimize.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabelMinimize.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelMinimizeMouseClicked(evt);
            }
        });
        jPanel1.add(jLabelMinimize);
        jLabelMinimize.setBounds(490, 10, 20, 20);

        jLabelClose.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        jLabelClose.setForeground(new java.awt.Color(40, 54, 85));
        jLabelClose.setText("X");
        jLabelClose.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabelClose.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelCloseMouseClicked(evt);
            }
        });
        jPanel1.add(jLabelClose);
        jLabelClose.setBounds(520, 10, 20, 20);

        LoginButton.setBackground(new java.awt.Color(77, 100, 141));
        LoginButton.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        LoginButton.setForeground(new java.awt.Color(40, 54, 85));
        LoginButton.setText("Login");
        LoginButton.setBorder(null);
        LoginButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        LoginButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LoginButtonMouseClicked(evt);
            }
        });
        LoginButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LoginButtonActionPerformed(evt);
            }
        });
        jPanel1.add(LoginButton);
        LoginButton.setBounds(410, 300, 70, 30);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 542, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 449, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    private int xMouse;
    private int yMouse;

    private void UserNameFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UserNameFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_UserNameFieldActionPerformed

    private void PassWordFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PassWordFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PassWordFieldActionPerformed

    private void CancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CancelButtonActionPerformed
        UserNameField.setText(null);
        PassWordField.setText(null);
    }//GEN-LAST:event_CancelButtonActionPerformed

    private void ForgotClickMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ForgotClickMouseClicked
        this.dispose();
    }//GEN-LAST:event_ForgotClickMouseClicked

    private void jLabelMinimizeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelMinimizeMouseClicked
        this.setState(JFrame.ICONIFIED);
    }//GEN-LAST:event_jLabelMinimizeMouseClicked

    private void jLabelCloseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelCloseMouseClicked
        System.exit(0);
    }//GEN-LAST:event_jLabelCloseMouseClicked

    private void LoginButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LoginButtonActionPerformed
     
    }//GEN-LAST:event_LoginButtonActionPerformed

    private void LoginButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LoginButtonMouseClicked
        System.out.println("adfdaf");
        String nume;
        String parola;
        String codedMessage = new String();
        String mesajServer = new String();
        if(PassWordField.getText().equals("")) {
            
            JOptionPane.showMessageDialog(null, "You forgot to set a pass",
                    "Pass", JOptionPane.CLOSED_OPTION);
        } else if(UserNameField.getText().equals("")) {
            
            JOptionPane.showMessageDialog(null, "You forgot to set a name",
                    "Name", JOptionPane.CLOSED_OPTION);
        } 
        else
        {
            nume = UserNameField.getText();
            parola = PassWordField.getText();
            codedMessage=codedMessage.concat("2;");
            codedMessage=codedMessage.concat(nume+";");
            codedMessage=codedMessage.concat(parola+';');
            client.send(codedMessage);
            mesajServer = client.read();
            
            //aici ai mesajul de la server     
            //daca codul e 0, atunci nu s-a reusit logarea
            //daca codul e 1, atunci s-a reusit logarea
            System.out.println(mesajServer);
            int cod=Integer.parseInt(mesajServer.substring(0,1));
            mesajServer=mesajServer.substring(2);
            switch (cod) {
                 case 0:{
                    JOptionPane.showMessageDialog(null, mesajServer,"Eroare", JOptionPane.CLOSED_OPTION);               
                    UserNameField.setText(null);
                    PassWordField.setText(null);
                    break;
                }
                case 1:{
                    JOptionPane.showMessageDialog(null, mesajServer,"OK", JOptionPane.CLOSED_OPTION);
                    this.dispose();
                    client.visible();
                    
                    break;
                }
                default:
                break;
            }

        }
    }//GEN-LAST:event_LoginButtonMouseClicked

    private void formMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMousePressed
      
        xMouse  = evt.getX();
        yMouse = evt.getY();
    }//GEN-LAST:event_formMousePressed

    private void formMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseDragged
        
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        this.setLocation(x - xMouse,y - yMouse);
    }//GEN-LAST:event_formMouseDragged
   
    
    /**
     * @param args the command line arguments
     */
    public static void mainn() {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(loginform.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(loginform.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(loginform.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(loginform.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new loginform().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton CancelButton;
    private javax.swing.JLabel ForgotClick;
    private javax.swing.JButton LoginButton;
    private javax.swing.JPasswordField PassWordField;
    private javax.swing.JTextField UserNameField;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabelClose;
    private javax.swing.JLabel jLabelImage;
    private javax.swing.JLabel jLabelMail;
    private javax.swing.JLabel jLabelMinimize;
    private javax.swing.JLabel jLabelName;
    private javax.swing.JLabel jLabelPASS;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanelaLogo;
    // End of variables declaration//GEN-END:variables
}