
package pao;

import javax.swing.JOptionPane;
import javax.swing.JFrame;


/**
 *
 * @author Jitca David
 */
public class singup extends javax.swing.JFrame {

    public singup() {
        initComponents();
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelSingup = new javax.swing.JPanel();
        jPanelLogo = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        UserNameField = new javax.swing.JTextField();
        jLabelMail = new javax.swing.JLabel();
        jLabelName = new javax.swing.JLabel();
        IDcompany = new javax.swing.JTextField();
        PassWordField = new javax.swing.JPasswordField();
        jLabelPASS = new javax.swing.JLabel();
        CancelButton = new javax.swing.JButton();
        LoginCLick = new javax.swing.JLabel();
        jLabelMinimize = new javax.swing.JLabel();
        jLabelClose = new javax.swing.JLabel();
        SingupButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Sing up");
        setUndecorated(true);

        jPanelSingup.setBackground(new java.awt.Color(208, 225, 249));
        jPanelSingup.setForeground(new java.awt.Color(77, 100, 141));
        jPanelSingup.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jPanelSingupMouseDragged(evt);
            }
        });
        jPanelSingup.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPanelSingupMousePressed(evt);
            }
        });
        jPanelSingup.setLayout(null);

        jPanelLogo.setBackground(new java.awt.Color(40, 54, 85));

        jLabel2.setIcon(new javax.swing.ImageIcon("E:\\Facultate\\SEM II\\ChessGame\\Image\\network.png")); // NOI18N

        jLabel4.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("ChessGame by MasterMinds");

        javax.swing.GroupLayout jPanelLogoLayout = new javax.swing.GroupLayout(jPanelLogo);
        jPanelLogo.setLayout(jPanelLogoLayout);
        jPanelLogoLayout.setHorizontalGroup(
            jPanelLogoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelLogoLayout.createSequentialGroup()
                .addContainerGap(50, Short.MAX_VALUE)
                .addGroup(jPanelLogoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(50, 50, 50))
        );
        jPanelLogoLayout.setVerticalGroup(
            jPanelLogoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelLogoLayout.createSequentialGroup()
                .addGap(107, 107, 107)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel4)
                .addContainerGap(176, Short.MAX_VALUE))
        );

        jPanelSingup.add(jPanelLogo);
        jPanelLogo.setBounds(0, 0, 254, 460);

        jLabel3.setFont(new java.awt.Font("Calibri", 0, 36)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Sing Up");
        jPanelSingup.add(jLabel3);
        jLabel3.setBounds(300, 50, 120, 60);

        UserNameField.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        UserNameField.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanelSingup.add(UserNameField);
        UserNameField.setBounds(290, 300, 190, 40);

        jLabelMail.setBackground(new java.awt.Color(77, 100, 141));
        jLabelMail.setFont(new java.awt.Font("Calibri", 1, 12)); // NOI18N
        jLabelMail.setForeground(new java.awt.Color(40, 54, 85));
        jLabelMail.setText("Company ID");
        jPanelSingup.add(jLabelMail);
        jLabelMail.setBounds(290, 130, 80, 16);

        jLabelName.setFont(new java.awt.Font("Calibri", 1, 12)); // NOI18N
        jLabelName.setForeground(new java.awt.Color(40, 54, 85));
        jLabelName.setText("User Name");
        jPanelSingup.add(jLabelName);
        jLabelName.setBounds(290, 280, 70, 16);

        IDcompany.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        IDcompany.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        IDcompany.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IDcompanyActionPerformed(evt);
            }
        });
        jPanelSingup.add(IDcompany);
        IDcompany.setBounds(290, 150, 190, 40);

        PassWordField.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        PassWordField.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        PassWordField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PassWordFieldActionPerformed(evt);
            }
        });
        jPanelSingup.add(PassWordField);
        PassWordField.setBounds(290, 220, 190, 40);

        jLabelPASS.setFont(new java.awt.Font("Calibri", 1, 12)); // NOI18N
        jLabelPASS.setForeground(new java.awt.Color(40, 54, 85));
        jLabelPASS.setText("Login Password");
        jPanelSingup.add(jLabelPASS);
        jLabelPASS.setBounds(290, 200, 100, 16);

        CancelButton.setBackground(new java.awt.Color(77, 100, 141));
        CancelButton.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        CancelButton.setForeground(new java.awt.Color(40, 54, 85));
        CancelButton.setText("Cancel");
        CancelButton.setBorder(null);
        CancelButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        CancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CancelButtonActionPerformed(evt);
            }
        });
        jPanelSingup.add(CancelButton);
        CancelButton.setBounds(300, 370, 70, 30);

        LoginCLick.setFont(new java.awt.Font("Calibri", 1, 12)); // NOI18N
        LoginCLick.setForeground(new java.awt.Color(40, 54, 85));
        LoginCLick.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LoginCLick.setText("Already register Click here to login");
        LoginCLick.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        LoginCLick.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LoginCLickMouseClicked(evt);
            }
        });
        jPanelSingup.add(LoginCLick);
        LoginCLick.setBounds(290, 420, 200, 16);

        jLabelMinimize.setFont(new java.awt.Font("Calibri", 1, 36)); // NOI18N
        jLabelMinimize.setForeground(new java.awt.Color(40, 54, 85));
        jLabelMinimize.setText("-");
        jLabelMinimize.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabelMinimize.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelMinimizeMouseClicked(evt);
            }
        });
        jPanelSingup.add(jLabelMinimize);
        jLabelMinimize.setBounds(490, 10, 20, 20);

        jLabelClose.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        jLabelClose.setForeground(new java.awt.Color(40, 54, 85));
        jLabelClose.setText("X");
        jLabelClose.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabelClose.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelCloseMouseClicked(evt);
            }
        });
        jPanelSingup.add(jLabelClose);
        jLabelClose.setBounds(520, 10, 20, 20);

        SingupButton.setBackground(new java.awt.Color(77, 100, 141));
        SingupButton.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        SingupButton.setForeground(new java.awt.Color(40, 54, 85));
        SingupButton.setText("Sing up");
        SingupButton.setBorder(null);
        SingupButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        SingupButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                SingupButtonMouseClicked(evt);
            }
        });
        SingupButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SingupButtonActionPerformed(evt);
            }
        });
        jPanelSingup.add(SingupButton);
        SingupButton.setBounds(410, 370, 70, 30);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelSingup, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 541, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelSingup, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 453, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
    private int xMouse;
    private int yMouse;
    
    private void IDcompanyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IDcompanyActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_IDcompanyActionPerformed

    private void PassWordFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PassWordFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PassWordFieldActionPerformed

    private void CancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CancelButtonActionPerformed
        IDcompany.setText(null);
        UserNameField.setText(null);
        PassWordField.setText(null);
    }//GEN-LAST:event_CancelButtonActionPerformed

    private void jLabelCloseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelCloseMouseClicked
            System.exit(0);
    }//GEN-LAST:event_jLabelCloseMouseClicked

    private void jLabelMinimizeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelMinimizeMouseClicked
        this.setState(JFrame.ICONIFIED);
    }//GEN-LAST:event_jLabelMinimizeMouseClicked

    private void SingupButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SingupButtonActionPerformed
        String nume;
        String parola;
        String mail;
               
    }//GEN-LAST:event_SingupButtonActionPerformed

    private void LoginCLickMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LoginCLickMouseClicked
        loginform lgf = new loginform();
        lgf.setVisible(true);
        lgf.setLocationRelativeTo(null);
        lgf.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.dispose();
    }//GEN-LAST:event_LoginCLickMouseClicked

    private void SingupButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SingupButtonMouseClicked
        String nume;
        String parola;
        String id;
        String codedMessage = new String();
        String mesajServer = new String();
        if(IDcompany.getText().equals("")) {
            
            JOptionPane.showMessageDialog(null, "You forgot to introduce your company id",
                    "Email", JOptionPane.CLOSED_OPTION);
        } else if(PassWordField.getText().equals("")) {
            
            JOptionPane.showMessageDialog(null, "You forgot to set a pass",
                    "Pass", JOptionPane.CLOSED_OPTION);
        } else if(UserNameField.getText().equals("")) {
            
            JOptionPane.showMessageDialog(null, "You forgot to set a name",
                    "Name", JOptionPane.CLOSED_OPTION);
        }
        else
        {
            nume = UserNameField.getText();
            parola = PassWordField.getText();
            id = IDcompany.getText();
            codedMessage=codedMessage.concat("1;");
            codedMessage=codedMessage.concat(nume+";");
            codedMessage=codedMessage.concat(parola+";");
            codedMessage=codedMessage.concat(id);
            client.send(codedMessage);
            mesajServer = client.read();
            
            
            //aici ai mesajul de la server     
            //daca codul e 0, atunci nu s-a reusit inregistrarea
            //daca codul e 1, atunci s-a reusit inregistrarea
            int cod=Integer.parseInt(mesajServer.substring(0,1));
            mesajServer=mesajServer.substring(2);
            switch (cod) {
                 case 0:{
                    JOptionPane.showMessageDialog(null, mesajServer,"Eroare", JOptionPane.CLOSED_OPTION);               
                    IDcompany.setText(null);
                    UserNameField.setText(null);
                    PassWordField.setText(null);
                    break;
                }
                case 1:{
                    JOptionPane.showMessageDialog(null, mesajServer,"OK", JOptionPane.CLOSED_OPTION);
                    this.dispose();
                    loginform.mainn();
                    break;
                }
                default:
                break;
            }
                   
        }
    }//GEN-LAST:event_SingupButtonMouseClicked

    private void jPanelSingupMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelSingupMousePressed
        System.out.println("adfsffdccxvg");
        xMouse  = evt.getX();
        yMouse = evt.getY();
    }//GEN-LAST:event_jPanelSingupMousePressed

    private void jPanelSingupMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelSingupMouseDragged
        
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        this.setLocation(x - xMouse,y - yMouse);
    }//GEN-LAST:event_jPanelSingupMouseDragged

    /**
     */
    public static void mainn() {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(singup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(singup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(singup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(singup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new singup().setVisible(true);
        });
        }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton CancelButton;
    private javax.swing.JTextField IDcompany;
    private javax.swing.JLabel LoginCLick;
    private javax.swing.JPasswordField PassWordField;
    private javax.swing.JButton SingupButton;
    private javax.swing.JTextField UserNameField;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabelClose;
    private javax.swing.JLabel jLabelMail;
    private javax.swing.JLabel jLabelMinimize;
    private javax.swing.JLabel jLabelName;
    private javax.swing.JLabel jLabelPASS;
    private javax.swing.JPanel jPanelLogo;
    private javax.swing.JPanel jPanelSingup;
    // End of variables declaration//GEN-END:variables
}
